In [1]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [2]:
c = torch.ones(3, 4)
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
c[0,1]

tensor(1.)

In [4]:
a = 1
t1 = torch.tensor(a)
t1

tensor(1)

In [5]:
b = [1, 2, 3]
t2 = torch.tensor(b)
t2

tensor([1, 2, 3])

### numpy 

In [6]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
# 共享内存
t = torch.from_numpy(arr)
t

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [7]:
arr[0][0] = 100
arr

array([[100,   2,   3],
       [  4,   5,   6]])

In [8]:
t

tensor([[100,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)

### 确定数值创建
+ layout: 内存中的布局形式，默认为strided，矩阵为稀疏矩阵时课使用sparse_coo
+ device: 所在设备是cpu还是gpu
+ requires_grad: 是否需要梯度

In [9]:
a = torch.zeros(3, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

+ torch.zeros_like(): 根据输入的张量生成同形状的张量
+ toch.ones(): 生成全1张量
+ toch.ones_like(): 根据输入的张量进行生成
+ torch.full(): 根据输入的数值x，生成全x的张量
+ torch.full_like(): 根据输入的数值x和张量进行生成

In [10]:
a = torch.zeros(3, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
a[0, 0] = 100
a

tensor([[100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

In [12]:
b = torch.zeros_like(a)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
c = torch.ones_like(a)
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.full((3, 4), 5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [15]:
d = torch.full_like(a, 5)
d

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

# 获取与存储

In [16]:
points = torch.full((3, 3), 6)
points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [17]:
torch.save(points, './data/t/ourpoints.t')

In [18]:
new_points = torch.load('./data/t/ourpoints.t')
new_points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [19]:
with open('./data/t/ourpoints.t', 'rb') as f:
    new_points = torch.load(f)
new_points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

### h5py库

In [20]:
!pip install h5py

In [21]:
points = torch.ones(3, 3)
points

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
# 存储数据
import h5py
f = h5py.File('./data/t/ourpoints.t', 'w')
dset = f.create_dataset('abc', data = points.numpy())
f.close()

In [23]:
# 读取数据
f = h5py.File('./data/t/ourpoints.t', 'r')
dset = f['abc']

# 恢复成 tensor
last_points = torch.from_numpy(dset[:])
f.close()
last_points

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
dset

<Closed HDF5 dataset>