# 基本操作
+ 拼接
+ 切分
+ 索引
+ 变换

In [1]:
import torch

## 拼接

In [2]:
# 两种拼接方法 cat() 和 stack()。cat()不会扩张张量的维度，stack()会扩张张量的维度
a = torch.normal(0,1,(3,4))
b = torch.normal(0,1,(3,4))
print(a)
print(b)

tensor([[ 0.5368, -0.4124,  0.5999,  0.4182],
        [ 0.2440, -0.2085,  0.5307, -2.6946],
        [-0.4502, -0.5342,  0.9499,  0.8953]])
tensor([[ 2.0324,  0.7434,  0.8093,  0.5623],
        [-0.1657, -1.7298,  0.4734, -0.9139],
        [ 0.3292,  1.3822,  0.4731, -0.9723]])


In [3]:
cat_ab1 = torch.cat([a,b], dim = 0)
cat_ab1

tensor([[ 0.5368, -0.4124,  0.5999,  0.4182],
        [ 0.2440, -0.2085,  0.5307, -2.6946],
        [-0.4502, -0.5342,  0.9499,  0.8953],
        [ 2.0324,  0.7434,  0.8093,  0.5623],
        [-0.1657, -1.7298,  0.4734, -0.9139],
        [ 0.3292,  1.3822,  0.4731, -0.9723]])

In [4]:
cat_ab2 = torch.stack([a,b], dim = 0)
cat_ab2

tensor([[[ 0.5368, -0.4124,  0.5999,  0.4182],
         [ 0.2440, -0.2085,  0.5307, -2.6946],
         [-0.4502, -0.5342,  0.9499,  0.8953]],

        [[ 2.0324,  0.7434,  0.8093,  0.5623],
         [-0.1657, -1.7298,  0.4734, -0.9139],
         [ 0.3292,  1.3822,  0.4731, -0.9723]]])

In [5]:
cat_ab2 = torch.stack([a,b], dim = 1)
cat_ab2

tensor([[[ 0.5368, -0.4124,  0.5999,  0.4182],
         [ 2.0324,  0.7434,  0.8093,  0.5623]],

        [[ 0.2440, -0.2085,  0.5307, -2.6946],
         [-0.1657, -1.7298,  0.4734, -0.9139]],

        [[-0.4502, -0.5342,  0.9499,  0.8953],
         [ 0.3292,  1.3822,  0.4731, -0.9723]]])

In [6]:
cat_ab3 = torch.stack([a,b], dim = 2)
cat_ab3

tensor([[[ 0.5368,  2.0324],
         [-0.4124,  0.7434],
         [ 0.5999,  0.8093],
         [ 0.4182,  0.5623]],

        [[ 0.2440, -0.1657],
         [-0.2085, -1.7298],
         [ 0.5307,  0.4734],
         [-2.6946, -0.9139]],

        [[-0.4502,  0.3292],
         [-0.5342,  1.3822],
         [ 0.9499,  0.4731],
         [ 0.8953, -0.9723]]])

## 切分

In [7]:
# chunk(input, chunks, dim = 0)按照指定的维度进行平均切分
# split(tensor, split_size_or_sections, dim = 0)可以指定切分的长度
a = torch.ones((3, 7))
a

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
chunked_a = torch.chunk(a, 3, 1)
chunked_a

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [9]:
splited_a1 = torch.split(a, 4, 1)
splited_a1

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [10]:
splited_a2 = torch.split(a, [2,4,1], 1)
splited_a2

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1.],
         [1.],
         [1.]]))

## 索引

In [11]:
# 使用范围索引
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [13]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [14]:
points[1:,0]

tensor([5., 2.])

In [15]:
# 维度提升一维，类似unsqueeze()
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [16]:
# torch.index_select(input, dim, index, out = None)在按照index序号，在指定的维度上索引
# torch.masked_select(input, mask, out = None)通过mask中为True的元素进行索引。通常这个方法时用来筛选数据。返回一维张量。
idx = torch.tensor([0, 2])
res = torch.index_select(points, dim = 0, index=idx)
res

tensor([[4., 1.],
        [2., 1.]])

In [17]:
# tensor.ge() 大于等于
mask = points.ge(3)
res = torch.masked_select(points, mask)
res

tensor([4., 5., 3.])

## 变换

In [18]:
# torch.reshape(input, shape) 改变张量的形状，新张量与旧张量共享内存
new_points = torch.reshape(points, [2, 3])
new_points

tensor([[4., 1., 5.],
        [3., 2., 1.]])

In [19]:
# torch.transpose(input, dim0, dim1) 交换张量的两个维度，交换也是共享内存
new_points = torch.transpose(points, 0, 1)
new_points

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [20]:
# torch.t(input)针对二维张量的转置而创建的，等价于 torch.transpose(input, 0, 1)
new_points = torch.t(points)
new_points

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [21]:
points = torch.ones(1,2,1,5)
points

tensor([[[[1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.]]]])

In [22]:
# torch.squeeze(input, dim = None, out = None)压缩张量中长度为1的维度
new_points = torch.squeeze(points)
new_points

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [23]:
# torch.unsqueeze(input, dim, out = None)依据dim扩展维度，扩展长度为1
new_points = torch.unsqueeze(points, -1)
new_points.size()

torch.Size([1, 2, 1, 5, 1])