#### storage方法访问内存

In [1]:
import torch

In [2]:
#storage()访问内存
points = torch.tensor([[4.0, 6.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 6.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [3]:
points_storage = points.storage()
points_storage[1]

6.0

#### 带下划线的操作

In [4]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [5]:
b = a.zero_()
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

#### 偏移量和步长

In [7]:
points = torch.tensor([[4.0, 1.0, 4.0, 2.0], [5.0, 3.0, 7.0, 8.0], [2.0, 1.0, 9.0, 5.0], [3.0, 8.0, 4.0, 5.0]])
second_point = points[1:, 1:]
second_point

tensor([[3., 7., 8.],
        [1., 9., 5.],
        [8., 4., 5.]])

In [8]:
points.storage_offset()

0

In [9]:
second_point.storage_offset()

5

In [10]:
points.stride()

(4, 1)

In [11]:
second_point.stride()

(4, 1)

In [12]:
# clone() 类似深拷贝
second_point = points[1:, 1:].clone()
second_point[0, 0] = 10.
second_point

tensor([[10.,  7.,  8.],
        [ 1.,  9.,  5.],
        [ 8.,  4.,  5.]])

In [13]:
second_point.storage_offset()

0

In [14]:
second_point.stride()

(3, 1)

#### 转置

In [15]:
points_new = torch.tensor([[4.0, 6.0], [5.0, 3.0], [2.0, 1.0]])
points_new

tensor([[4., 6.],
        [5., 3.],
        [2., 1.]])

In [16]:
points_t = points_new.t()
points_t

tensor([[4., 5., 2.],
        [6., 3., 1.]])

In [17]:
points_new.stride()

(2, 1)

In [18]:
points_t.stride()

(1, 2)

#### 连续张量
+ 连续张量：张量的顺序与存储顺序一致
+ 有些操作只针对连续张量有作用

In [19]:
points_new.is_contiguous()

True

In [20]:
points_t.is_contiguous()

False

In [21]:
# contiguous()方法将非连续张量转换成连续张量
points_t_cont = points_t.contiguous()
points_t_cont.is_contiguous()

True